### ISSUE TITLE
a plugin had an unrecoverable error, will restart plugin

### ISSUE THREAD

**Issue by robinmedland** [jurek7/logstash-input-mqtt#12]
I am using this plugin in logstash, when i send a message to a topic i get this error in my logstash.

[2018-10-29T12:32:01,545][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-10-29T12:33:25,933][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:test
  Plugin: <LogStash::Inputs::Mqtt topic=>"Temp", id=>"927edf5a640ae69f98f5d0b257e350a084fb548c257e946aa98bb0e2e6e3c823", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_7991415a-8e06-4683-b4b7-ed87a3d7bbfd", enable_metric=>true, charset=>"UTF-8">, mqttHost=>"localhost", port=>1883, ssl=>false, client_id=>"logstash-mqtt-input5zts", clean_session=>true, qos=>0>
  Error: Direct event field references (i.e. event['field']) have been disabled infavor of using event get and set methods (e.g. event.get('field')). Please consultthe Logstash 5.0 breaking changes documentation for more details.
  Exception: NoMethodError
  Stack: C:/logstash/logstash-6.4.2/logstash-core/lib/logstash/event.rb:43:in `method_missing'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-input-mqtt-0.0.2/lib/logstash/inputs/mqtt.rb:63:in `block in run'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-codec-plain-3.0.6/lib/logstash/codecs/plain.rb:35:in `decode'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-input-mqtt-0.0.2/lib/logstash/inputs/mqtt.rb:62:in `block in run'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/mqtt-0.5.0/lib/mqtt/client.rb:405:in `block in get'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/mqtt-0.5.0/lib/mqtt/client.rb:437:in `block in get_packet'
org/jruby/RubyKernel.java:1292:in `loop'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/mqtt-0.5.0/lib/mqtt/client.rb:435:in `get_packet'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/mqtt-0.5.0/lib/mqtt/client.rb:404:in `get'
C:/logstash/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-input-mqtt-0.0.2/lib/logstash/inputs/mqtt.rb:61:in `run'
C:/logstash/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:409:in `inputworker'
C:/logstash/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:403:in `block instart_input'

**Comment by jmcarvalho** [comment]
Hi @robinmedland! I am trying to use this plugin but I am getting the same error as you. Did you manage to solve this?
